name: Hello World!

on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Print date
        run: |
          echo "Today is (date)"
      - name: Print dir
        run: |
          echo "Current directory is: (ls)"
